data <- read.table("E:/Vejay/vejay/Courses/Coursera/Data Science/4 Exploratory Data Analysis/exdata_2Fdata%2Fhousehold_power_consumption/household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
striptime <- strptime(data$Date, format = "%d/%m/%Y")
data$Date <- as.Date(striptime, "%d-%m-%y")
req_data <- subset(data,Date >= "2007-2-1" & Date <= "2007-2-2")
Date_Time <-as.POSIXct(paste(req_data$Date, req_data$Time))
req_data <- cbind(Date_Time,req_data)
par(mfrow=c(2,2), mar=c(4,4,4,4))
plot(req_data$Global_active_power~req_data$Date_Time, type="l", col="black", xlab="", ylab= "Global Active Power")
plot(req_data$Voltage~req_data$Date_Time, type = "l", ylab="Voltage", xlab="datetime")
plot(req_data$Sub_metering_1~Date_Time, col = "Black" , type="l", ylab="Energy sub metering", xlab="")
lines(req_data$Sub_metering_2~Date_Time,col="Red")
lines(req_data$Sub_metering_3~Date_Time,col="Blue")
legend("topright", col=c("Black", "Red", "Blue"),c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = "solid")
plot(req_data$Global_reactive_power~req_data$Date_Time, type = "l", ylab="Global_rective_power",xlab="datetime")
dev.copy(png,"plot4.png", width=480, height=480)
dev.off()
